### ISSUE TITLE
README.md doesn't compile

### ISSUE THREAD

**Issue by enoy19** [Marcel-Lambacher/UdemyDownloader#1]
Hello Mr. Lambacher,

your code doesn't compile when I run: DCC32.EXE README.md

please fix immediately or I will unstar your project.

**Comment by Marcel-Lambacher** [comment]
Dear Customer,

thank you for your feedback.

Unfortunately, the file "README.md" isn't written in Delphi.
To run this software you've to install a turbo assembler environment.
After this, you can build and link it using tasm.exe and tlink.exe

Sincerely

Marcel Lambacher
